### PR TITLE
Aglu tempdata

### LINKED ISSUE #729: Handle temp-data-inject tracebacks for land input 2-3-4-5 files

### PR DESCRIPTION
**Pull request by kvcalvin**
Remove temp-data-inject files from land. 

Note this replaces https://github.com/JGCRI/gcamdata/pull/841 which had some sort of problem.

Closes #729

### CODE REVIEW

File: R/zchunk_L2252.land_input_5_irr_mgmt.R [hunk 1]
```diff
@@ -256,26 +322,64 @@ module_aglu_L2252.land_input_5_irr_mgmt <- function(command, ...) {
...
+      mutate(ghost.unnormalized.share = round(landshare, aglu.DIGITS_LAND_USE)) %>%
+      select(-landshare) %>%
+      # For bio techs with no ghost share info, set irr to 0 and rfd to 1
+      mutate(ghost.unnormalized.share = if_else(is.na(ghost.unnormalized.share) & Irr_Rfd == "RFD", 1, ghost.unnormalized.share)) %>%
+      mutate(ghost.unnormalized.share = if_else(is.na(ghost.unnormalized.share) & Irr_Rfd == "IRR", 0, ghost.unnormalized.share)) %>%
+      select(c(LEVEL2_DATA_NAMES[["LN5_NodeGhostShare"]])) ->
       L2252.LN5_NodeGhostShare
 
+    if( OLD_DATA_SYSTEM_BEHAVIOR ) {
+      # For some reason, the Node Ghost Share for SinaiP in Africa_Northern in the old data system is missing.
```
Comment (bpbond) [inline R/zchunk_L2252.land_input_5_irr_mgmt.R]: Ha!

**Comment by bpbond** [comment]
@kvcalvin If you're happy with this please provide link to original PR and then we can merge it. THANK YOU for all the work on this!

**Comment by bpbond** [comment]
Could this be fixed before merging please?
```
[1] "module_aglu_L2252.land_input_5_irr_mgmt"
[1] "- make 8.78"
Inputs aglu/A_LandLeaf3, L181.YieldMult_R_bio_GLU_irr don't appear as precursors for any outputs - chunk module_aglu_L2252.land_input_5_irr_mgmt
```
